from __future__ import annotations

from pathlib import Path
import unittest


class ConceptGraphsPreprocessOrderTests(unittest.TestCase):
    def test_engineered_runner_filters_before_mask_subtraction(self) -> None:
        source = Path("examples/run_conceptgraphs_engineered_parity.py").read_text(encoding="utf-8")
        self.assertIn('"mask_subtract_order": "conceptgraphs_filter_then_subtract"', source)
        self.assertIn("--frame-limit", source)
        self.assertIn("--frame-stride", source)
        self.assertIn("--export-clip-min-margin", source)
        self.assertIn("--export-split-policy", source)
        self.assertIn("--export-split-min-centroid-separation", source)
        self.assertIn("--export-split-min-scene-split-rate", source)
        self.assertIn("--multires-export", source)
        self.assertIn("--multires-fine-split-by-label", source)
        self.assertIn("--multires-fine-takeover-min-points", source)
        self.assertIn("--multires-replacement-mode", source)
        self.assertIn('"risky-replace"', source)
        self.assertIn('"retained_takeover_candidate_counts"', source)
        self.assertIn("--geometry-repair-vent-to-sofa-delta", source)
        self.assertIn("--geometry-repair-cushion-shrink-radius", source)
        self.assertIn("apply_geometry_repairs", source)
        self.assertIn("--geometry-repair-large-label-rules", source)
        self.assertIn("--geometry-repair-large-label-evidence-mode", source)
        self.assertIn("--geometry-repair-large-label-source-mode", source)
        self.assertIn("--geometry-repair-large-label-require-target-declared", source)
        self.assertIn("--geometry-repair-large-label-min-observations", source)
        self.assertIn("--geometry-repair-large-label-min-source-share", source)
        self.assertIn('"declared-source-or-clip"', source)
        self.assertIn('"target-declared-geometry"', source)
        self.assertIn('"carrier-v2"', source)
        self.assertIn('"geometry_authorized"', source)
        self.assertIn('"blocked_relabel_counts"', source)
        self.assertIn('"source_miss_counts"', source)
        self.assertIn('"shape_fail_counts"', source)
        self.assertIn('"large_label_source_mode"', source)
        self.assertIn("top_repair_score_labels", source)
        self.assertIn("parse_large_label_relabel_rules", source)
        self.assertIn('"large_label_relabel_rules"', source)
        self.assertIn('"geometry_repair_probe"', source)
        self.assertIn("--geometry-repair-keep-mode", source)
        self.assertIn("--geometry-repair-keep-auto-min-count", source)
        self.assertIn("--geometry-repair-scale-prior-mode", source)
        self.assertIn("--geometry-repair-scale-prior-tolerance", source)
        self.assertIn("--geometry-repair-scale-prior-min-target-share", source)
        self.assertIn("--geometry-repair-scale-prior-max-source-share", source)
        self.assertIn('"declared-auto"', source)
        self.assertIn('"log-only"', source)
        self.assertIn("derive_auto_keep_labels", source)
        self.assertIn("scale_prior_violation", source)
        self.assertIn("select_scale_prior_target", source)
        self.assertIn('"scale_prior_probe"', source)
        self.assertIn("--geometry-repair-scale-prior-hard-ratio", source)
        self.assertIn('"clip-compatible-fallback"', source)
        self.assertIn('"hard_violation_ratio"', source)
        self.assertIn('"keep_mode_diagnostics"', source)
        self.assertIn('"violations_by_label"', source)
        self.assertIn('"abstain_reasons"', source)
        self.assertIn("--cg-merge-label-gate", source)
        self.assertIn("--cg-merge-label-gate-min-share", source)
        self.assertIn("--cg-merge-label-gate-min-obs", source)
        self.assertIn("--cg-merge-label-gate-mutual-thresh", source)
        self.assertIn('"mutual_containment"', source)
        self.assertIn('"merge_label_gate_mutual_thresh"', source)
        self.assertIn('"declared_label_counts"', source)
        self.assertIn("merge_objects_with_label_gate", source)
        self.assertIn("label_cluster_veto", source)
        self.assertIn('"cg_merge_label_gate_probe"', source)
        self.assertIn('"legacy_merge_candidate_pairs"', source)
        self.assertIn('"vetoed_pairs"', source)
        self.assertIn('"veto_label_pairs"', source)
        self.assertIn('"merge_label_gate"', source)
        self.assertIn("apply_multires_replacement", source)
        self.assertIn("multires_export_probe", source)
        self.assertIn("summarize_export_split_decisions", source)
        self.assertIn("--l2-retire-after-misses", source)
        self.assertIn("--l2-relation-bonus-weight", source)
        keep_pos = source.index("pre_keep_indices.append(det_i)")
        subtract_pos = source.index("mask_subtract_contained(xyxy[pre_keep_indices], frame_masks)")
        project_pos = source.index("world_points_from_mask_arrays(mask, depth, rgb_image, pose)")
        self.assertLess(keep_pos, subtract_pos)
        self.assertLess(subtract_pos, project_pos)

    def test_gt_monitor_uses_same_preprocess_order_as_runner(self) -> None:
        source = Path("examples/run_conceptgraphs_gt_layer_monitor.py").read_text(encoding="utf-8")
        self.assertIn('"mask_subtract_order": "conceptgraphs_filter_then_subtract"', source)
        keep_pos = source.index("pre_keep_indices.append(det_i)")
        subtract_pos = source.index("mask_subtract_contained(xyxy[pre_keep_indices], frame_masks)")
        project_pos = source.index("world_points_from_mask_arrays(mask, depth, pose)")
        self.assertLess(keep_pos, subtract_pos)
        self.assertLess(subtract_pos, project_pos)


if __name__ == "__main__":
    unittest.main()
