from __future__ import annotations

"""Physical scale priors for evaluator-facing semantic-authority checks.

The carrier-readout failure family behind the E70 gains is one physical
principle: a small-object label (tissue-paper, bin) sitting on a geometry
carrier whose extent the label cannot plausibly reach.  Instead of hand-written
`source:target:threshold` rules, these helpers derive repairs from a per-label
max-extent prior plus the object's own multi-view declared-label distribution.

Provenance of DEFAULT_MAX_EXTENT_PRIORS: commonsense physical size upper bounds
(longest bounding-box side, meters) generated by a language model from the class
names alone, frozen before any evaluation, and deliberately generous — the
violation check should only fire when an object is clearly larger than its
readout label could plausibly be.  No Replica ground truth, scene identity, or
evaluation feedback was used to set these numbers.
"""


DEFAULT_MAX_EXTENT_PRIORS: dict[str, float] = {
    "basket": 0.9,
    "bed": 2.6,
    "bench": 2.6,
    "bin": 0.9,
    "blanket": 2.2,
    "blinds": 3.0,
    "book": 0.5,
    "bottle": 0.5,
    "bowl": 0.5,
    "box": 1.2,
    "cabinet": 2.6,
    "camera": 0.4,
    "candle": 0.4,
    "chair": 1.3,
    "clock": 0.6,
    "cloth": 2.2,
    "comforter": 2.6,
    "cushion": 1.0,
    "desk": 2.6,
    "desk-organizer": 0.5,
    "indoor-plant": 2.2,
    "lamp": 1.8,
    "monitor": 1.1,
    "nightstand": 1.0,
    "panel": 3.0,
    "picture": 1.6,
    "pillar": 4.0,
    "pillow": 1.0,
    "pipe": 3.0,
    "plant-stand": 1.0,
    "plate": 0.4,
    "pot": 0.7,
    "rug": 3.5,
    "sculpture": 1.6,
    "shelf": 2.6,
    "sofa": 3.2,
    "stool": 0.9,
    "switch": 0.3,
    "table": 3.2,
    "tablet": 0.5,
    "tissue-paper": 0.45,
    "tv-screen": 2.0,
    "tv-stand": 2.0,
    "vase": 0.7,
    "vent": 1.2,
    "wall-plug": 0.25,
}


def scale_prior_violation(
    pred_label: str,
    max_extent: float,
    *,
    priors: dict[str, float] | None = None,
    tolerance: float = 1.0,
) -> dict[str, object]:
    """Check whether an object's extent is implausible for its readout label.

    Returns a diagnostics dict with `violation` set when
    ``max_extent > prior[pred_label] * tolerance``.  Labels without a prior
    never violate (unknown classes keep their readout authority).
    """
    priors = DEFAULT_MAX_EXTENT_PRIORS if priors is None else priors
    prior = priors.get(str(pred_label or ""))
    diagnostics: dict[str, object] = {
        "violation": False,
        "pred_label": str(pred_label or ""),
        "max_extent": round(float(max_extent), 6),
        "prior_max_extent": None if prior is None else round(float(prior), 6),
        "tolerance": round(float(tolerance), 6),
    }
    if prior is None or not pred_label:
        diagnostics["reason"] = "no_prior_for_label"
        return diagnostics
    limit = float(prior) * float(tolerance)
    diagnostics["limit"] = round(limit, 6)
    if float(max_extent) > limit:
        diagnostics["violation"] = True
        diagnostics["reason"] = "extent_exceeds_prior"
    else:
        diagnostics["reason"] = "extent_within_prior"
    return diagnostics


def select_scale_prior_target(
    declared_label_counts: dict[str, int],
    max_extent: float,
    *,
    priors: dict[str, float] | None = None,
    min_target_share: float = 0.15,
    max_source_share: float = 1.0,
    source_label: str = "",
    excluded_labels: frozenset[str] | set[str] = frozenset(),
) -> dict[str, object]:
    """Choose a replacement label from the object's own multi-view evidence.

    Candidates are the object's declared labels whose scale prior accommodates
    the observed extent, ranked by declared share.  Selection abstains (returns
    ``target == ""``) when: no declared evidence, no candidate fits the extent,
    the best candidate's share is below ``min_target_share``, or the current
    source label itself is well supported by multi-view evidence
    (``source_share > max_source_share`` — consistent multi-view semantics keep
    authority even when the extent looks unusual; this is the room0
    cushion-carrier guard).
    """
    priors = DEFAULT_MAX_EXTENT_PRIORS if priors is None else priors
    counts: dict[str, int] = {}
    total = 0
    for label, raw_count in (declared_label_counts or {}).items():
        try:
            count = int(raw_count)
        except (TypeError, ValueError):
            continue
        if count <= 0:
            continue
        counts[str(label)] = count
        total += count
    source_share = (counts.get(str(source_label), 0) / total) if total else 0.0
    diagnostics: dict[str, object] = {
        "target": "",
        "target_share": 0.0,
        "source_share": round(source_share, 6),
        "candidates": [],
        "abstain_reason": "",
    }
    if total == 0:
        diagnostics["abstain_reason"] = "no_declared_evidence"
        return diagnostics
    if source_share > max_source_share:
        diagnostics["abstain_reason"] = "source_well_supported"
        return diagnostics
    ranked: list[tuple[float, str]] = []
    for label, count in counts.items():
        if label == source_label or label in excluded_labels:
            continue
        prior = priors.get(label)
        if prior is None or float(max_extent) > float(prior):
            continue
        ranked.append((count / total, label))
    ranked.sort(key=lambda item: (-item[0], item[1]))
    diagnostics["candidates"] = [
        {"label": label, "share": round(share, 6)} for share, label in ranked[:5]
    ]
    if not ranked:
        diagnostics["abstain_reason"] = "no_scale_compatible_declared_target"
        return diagnostics
    best_share, best_label = ranked[0]
    if best_share < min_target_share:
        diagnostics["abstain_reason"] = "target_share_below_minimum"
        return diagnostics
    diagnostics["target"] = best_label
    diagnostics["target_share"] = round(best_share, 6)
    return diagnostics
